### ISSUE TITLE
Convert cards.json from JSON array to JSON object

### ISSUE THREAD

**Issue by Bebersohl** [Bebersohl/hp-redux#1]
We need cards.json to be a JSON object so that the lookup time of a card is O(1) rather than O(n). Use the card id as the key (also leave the id as a value in the card object as well).

The properties should be sorted alphabetically.

It should look like this:
```JSON
{
  "KARA_00_07": {
    "cost": 1,
    "dbfId": 39762,
    "id": "KARA_00_07",
    "name": "Astral Portal",
    "playRequirements": {
    "REQ_NUM_MINION_SLOTS": 1
    },
    "playerClass": "MAGE",
    "set": "KARA",
    "text": "Summon a random <b>Legendary</b> minion.",
    "type": "SPELL"
  },
  "NEW1_008a": {
    "cost": 0,
    "dbfId": 313,
    "id": "NEW1_008a",
    "name": "Ancient Teachings",
    "playerClass": "DRUID",
    "set": "EXPERT1",
    "text": "Draw a card.",
    "type": "SPELL"
  },
  ...
```

Write a js file to convert the array  in a new root folder called `tasks` along with unit tests (in test folder).

**Comment by Bebersohl** [comment]
@ericebersohl wanna try this one? I can provide more direction if needed.

**Comment by ericebersohl** [comment]
I understand what needs to be done, but I don't know how to write a script to make it happen.  I'll give it a shot if you let me know what tool you think would work best.

**Comment by Bebersohl** [comment]
@ericebersohl By script I really meant js file. To do this task you could:
1. Import in `cards.js`
2. Manipulate and sort the data into a new object
3. `JSON.stringify` the object
4. Use `fs` to write the stringified object to a new json file (`fs` is a built in node module for file system operations. The finished json file should be called `cards.json` so you should rename the one we have now to something else)

**Comment by ericebersohl** [comment]
Alright, I'll work on it today.
