### ISSUE TITLE
implement GAIN_MANA action

### ISSUE THREAD

**Issue by Bebersohl** [Bebersohl/hp-redux#20]
`GAIN_MANA` gives a player mana.

The `gainMana` action creator should take a player id and the amount of mana to gain (default to 1). Players reducer should handle this action.

Player's `mana` cannot exceed `maxMana`. If the amount gained will exceed `maxMana` then set player's mana to `maxMana`.

Steps to implement actions can be found [here](https://github.com/Bebersohl/hp-redux/blob/master/CONTRIBUTING.md)

**Comment by Bebersohl** [comment]
@ericebersohl Wanna do this one?

**Comment by ericebersohl** [comment]
I'm on it boss.

**Comment by ericebersohl** [comment]
So I know that Wild Growth gives the Excess Mana card when you use it at 10 mana.  Is that a feature that's specific to that card, or is it something that needs to be handled by GAIN_MANA?

**Comment by ericebersohl** [comment]
It might be a day or two before I tackle this one.  I've decided to work through a [tutorial ](https://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html#the-architecture)so I have a better grasp of react/redux.

**Comment by Bebersohl** [comment]
sounds good
