### ISSUE TITLE
implement SHUFFLE_CARD action

### ISSUE THREAD

**Issue by Bebersohl** [Bebersohl/hp-redux#23]
`SHUFFLE_CARD` shuffles a card into a player's deck.

`SHUFFLE_CARD` action creator takes card id and player id and a boolean called `removeFromHand`.

if `removeFromHand` is true then remove the card id from the players hand. Otherwise leave the player's hand alone.

NOTE: this action should only randomize the position of the new card id, all the other cards in the player's deck should remain in the same order.

Player reducer should handle `SHUFFLE_CARD`.

**Comment by ericebersohl** [comment]
@Bebersohl I've got a working version of this action, but I'm not sure my tests are adequate.  Currently I'm only testing to make sure that the deck and/or hand arrays have all the necessary cards.  I don't know how to test the "shuffle" part of this action.

Suggestions?

**Comment by Bebersohl** [comment]
It's really hard to test randomness. Just test the deck to make sure it
includes the right cards.

**Comment by ericebersohl** [comment]
I wrote a quick script to count the values the Math.random() formula put out, it works as intended.
