### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by ericebersohl** [Bebersohl/hp-redux#31]
There aren't any comments in our code.  Supposedly, commenting is a programming best practice.  Do you think this is going to cause problems later?

**Comment by Bebersohl** [comment]
Maybe, but I don't think it's that big of a deal because there are only 2 people contributing right now and because the redux pattern is straight forward once you understand it.  I'd say the only time we really need to add comments is when we deviate from the standard redux architecture.

**Comment by ericebersohl** [comment]
That seems fair enough.  Maybe when we start implementing react/socket.io/etc. we'll need to reevaluate.
